### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by jakkritz** [Rennbon/pyhikvision#4]
When I ran face_captured.py on Ubuntu, I got this:
```
Traceback (most recent call last):
  File "face_captured.py", line 33, in <module>
    data = adapter.setup_alarm_chan_v31(callbacks.msg_callback_v31(face_captured_cb), None)
TypeError: argument must be callable or integer function address
```
Also instant_preview.py
```
Traceback (most recent call last):
  File "face_captured.py", line 33, in <module>
    data = adapter.setup_alarm_chan_v31(callbacks.msg_callback_v31(face_captured_cb), None)
TypeError: argument must be callable or integer function address
```

Any idea what went wrong?

Thanks,

PS. I'm forking to translate it into English. Hope it's ok with you.

**Comment by Rennbon** [comment]
It's ok now, I didn't debug it well before.

**Comment by XiongZiRan** [comment]
When I ran sdk_state.py on Ubuntu, I got this error:

> loop[2] find 2 mac and 2 ip
ERROR:root:NET_DVR_Login_V40 用户登录失败: the error code is 29
ERROR:root:common_start 失败: the error code is29
ERROR:root:初始化Adapter失败

Any idea what went wrong?

Thanks

**Comment by Rennbon** [comment]
> When I ran sdk_state.py on Ubuntu, I got this error:
> 
> > loop[2] find 2 mac and 2 ip
> > ERROR:root:NET_DVR_Login_V40 用户登录失败: the error code is 29
> > ERROR:root:common_start 失败: the error code is29
> > ERROR:root:初始化Adapter失败
> 
> Any idea what went wrong?
> 
> Thanks

The offical SDK support for Unbuntu is not vary friendly.
