### ISSUE TITLE
调用instant_preview.py登录成功但是回调函数里面没有执行获取不到数据

### ISSUE THREAD

**Issue by WestbrookZero** [Rennbon/pyhikvision#8]
在Windows下的控制台输出如下：
Login successful,the userId is  0
start preview 成功 0
callback 1

**Comment by Rennbon** [comment]
win是几位的

**Comment by WestbrookZero** [comment]
win64

**Comment by 114000** [comment]
你好，这个问题现在有进展吗，我也遇到了相同的情况

**Comment by qiufp** [comment]
到海康威视官网下载新版本的SDK（设备网络SDK_Win64 V6.1.6.45_build20210302）来替换，可以获取到数据

**Comment by cyjdlhy** [comment]
您好 ，请问还有交流的群号吗？实在有太多问题百思不得其解，
