### ISSUE TITLE
Linux 无法登录

### ISSUE THREAD

**Issue by cc-tse** [Rennbon/pyhikvision#9]
旧版6.0 sdk 会出错误 41
新旧6.1 sdk 会出错误 29

经查可能是 sdk 位置问题， 执行 NET_DVR_SetSDKInitCfg 后正常， 如下

![无标题](https://user-images.githubusercontent.com/67247116/86312639-c44f6100-bc55-11ea-9c7d-a2b887525085.png)

请检查

**Comment by Rennbon** [comment]
新的SDK需要看下参数请求

**Comment by Rennbon** [comment]
python 3环境，你看看是不是版本的问题

**Comment by Rennbon** [comment]
版本支持到2020年3月份的sdk,readme中有提供

**Comment by Rennbon** [comment]
已同步到最新版本
